@jwt = {{login.response.body.access_token}}

###
# @name register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "276 2"
}

###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "Pham Thanh Dong"
}

###
# @name getMe
GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer {{jwt}}